### ISSUE TITLE
Pre meeting countdown issue

### ISSUE THREAD

**Issue by AndyZBell** [AntonyCorbett/OnlyT#345] opened 2019-10-20 19:52 UTC
**Describe the bug**
 We are using Only-T on its own dedicated monitor. We have 3 monitors - one that the PC operator uses, the projector and the timing monitor. 

However, if we enable the countdown timer then sometimes, when the timer finishes, the screen goes white and displays nothing. 

The only workaround we have found to get the timer to redisplay is:

1) turn off the dedicated screen
2) close the Only-T app
3) start the Only-T app
4) turn on the dedicated screen 

**To reproduce the error**

1) In settings point Only-T to its dedicated monitor
2) Enable the countdown timer
3) Point the countdown timer to the dedicated screen (the same one as step 1)
4) Enter the meeting times
5) Have the system up and running in time for the countdown timer to display

**Expected behavior**
The countdown timer should display and countdown to zero. Then the regular display should be shown - we have the analog clock. 

**Screen Shots**
N/a

**Desktop (please complete the following information):**
 - Windows version - 10
 - 3 monitors, as described above. Dedicated graphics cars that supports 3 monitors natively.

**Comment by AntonyCorbett** [comment] 2019-10-21 07:14
@AndyZBell If I understand correctly, you have set the OnlyT main monitor _and_ countdown monitor to the same device. and this _sometimes_ means that when the countdown concludes the device shows a white screen. Couple of questions:

1. What version of OnlyT are you using?
2. Please estimate how often this happens (I have tried a few times but have been unable to reproduce it yet).

Thanks
Antony

**Comment by AndyZBell** [comment] 2019-10-21 08:17
Hi Anthony

Yes, you understand the issue correctly.

Of late it’s happening at every meeting.

I’m next at the hall tomorrow - I’ll check the version number and upgrade if we’re not on the latest version. I’ll let you know what happens...

I’m not sure if this is a hardware or software issue or both. Windows 10 seems quite flaky when it comes to allocating video resources. Yesterday, Only-M displayed the pictures nicely and seemed to hand back control to jw library - the year text displayed in the screen. Yet jw library wouldn’t display the song and there was no audio. I had to restart jw library to get it working again.

Tbh I wish soundbox was still supported/allowed - one program vs several...

Andy

**Comment by AntonyCorbett** [comment] 2019-10-21 12:32
@AndyZBell It sounds like Window replaced your video driver during a recent update. Perhaps you can try to update it by downloading a driver from the manufacturer's website.

**Comment by AndyZBell** [comment] 2019-10-21 15:27
Thanks Anthony. We’ll try updating the driver...

**Comment by AntonyCorbett** [comment] 2019-11-13 15:47
@AndyZBell Closing for now. Please re-open if needed.

**Closed by AntonyCorbett** 2019-11-13 15:47 UTC
Labels: question
