### ISSUE TITLE
Apply Yourself times missing

### ISSUE THREAD

**Issue by EnglishIrishman** [AntonyCorbett/OnlyT#333] opened 2019-08-23 18:05 UTC
When running OnlyT, the 'Apply Yourself To The Field Ministry' times would not display. This persisted even when reinstalling the software.

I worked out the problem was with the feed.json file in the users AppData. As this remains after uninstall the problem still occurs after reinstalling. Deleting the feed.json file forced OnlyT to re-download the file and this fixed the issue.

It might be worth either removing the file when the user runs the uninstall (to force a new file on reinstall) or add a 'manual update' option in the settings to force an update of the timing feed in case other users experience this in the future.

Sorry, I didn't grab any screenshots as I had to work out the fix quickly during a meeting ;)

**Comment by AntonyCorbett** [comment] 2019-08-23 18:14
@EnglishIrishman thanks. I don't suppose you have a copy of the feed.json file before you deleted it? I'm interested in what way it was corrupted.

**Comment by EnglishIrishman** [comment] 2019-08-23 18:21
[feed.zip](https://github.com/AntonyCorbett/OnlyT/files/3535731/feed.zip)

**Comment by AntonyCorbett** [comment] 2019-08-24 09:47
@EnglishIrishman The problem is caused by the "last changed" date stamp of the file (which is some months in the future). I guess the feed.jspn was probably created when the PC's system clock had been advanced for some reason.

**Comment by AntonyCorbett** [comment] 2019-08-24 09:51
@EnglishIrishman Fixed in latest pre-release. Thanks for your help.

**Closed by AntonyCorbett** 2019-08-24 09:51 UTC
Labels: bug
