### ISSUE TITLE
Media on the time screen

### ISSUE THREAD

**Issue by jumper7777** [AntonyCorbett/OnlyT#234] opened 2018-12-18 20:33 UTC
Hello Is it possible to display photos from the media screen on the time screen? There is a place on it, and it was a very useful option for the lecturer

**Comment by AntonyCorbett** [comment] 2018-12-19 08:31
@jumper7777 no, not easily.

**Comment by AntonyCorbett** [comment] 2018-12-19 09:10
@jumper7777 you could compose the display yourself using OBS or similar software but it's not straightforward. Alternatively, we could modify OnlyT to include a small panel reproducing the content of a specified monitor, but the panel would be quite small and would _always_ display content (e.g. in the case of reproducing the media monitor in a KH setting, there is no way to automatically detect when JWL is showing media rather than simply the year text).

**Comment by jumper7777** [comment] 2018-12-19 09:19
I understand that the preview would be all the time 
Yesterday the photo I sent showed a great place to put it. 
In the options, for example, make a choice if you want to have a preview of the media screen or the current time of the digital clock
 Very complicated?

**Comment by AntonyCorbett** [comment] 2018-12-19 10:05
@jumper7777 Thanks for your suggestion. I didn't receive a photo but I understand where the proposed optional preview would be located. It's feasible to take a periodic screenshot of the media monitor and use that as a preview image, but painting a live reproduction (as SoundBox 3.1 did) is problematic on some systems. So it would work ok for images but videos would appear "stuck". Another option is to incorporate an NDI receiver window and use NewTek's scan converter to capture the media monitor.

**Comment by AntonyCorbett** [comment] 2018-12-22 18:00
A fairly straightforward and free workaround exists - use NewTek's Scan Converter to make the PC's displays available as NDI sources. Then load NDI Studio Monitor, specify the media display as it's source, set it as "Always on top" and position it where you like on top of the timer display.

**Comment by ucphinni** [comment] 2018-12-22 23:54
Newteck scan converter requires an Instruction set not all cpus support. In these cases, OBS can be used as an alternative because it is not compiled to take advantage of latest instruction set on underpowered processors.
________________________________

**Comment by AntonyCorbett** [comment] 2018-12-25 12:50
Thanks for all your valuable feedback. However, I don't propose to implement this feature at this stage so I will close the issue. We have no idea what JWL developments will bring so I want to try to limit the feature-set of OnlyX applications to essentials. There appear to be a couple of work-arounds discussed above.

**Closed by AntonyCorbett** 2018-12-25 12:50 UTC
