### ISSUE TITLE
Onlt T

### ISSUE THREAD

**Issue by TechMan88** [AntonyCorbett/OnlyT#482] opened 2023-03-29 12:59 UTC
On my computer only T is not remembering the display Monitor.  I set it ,and days later it revert to no monitor. **Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment] 2023-03-29 18:50
@TechMan88 it’s difficult to state with certainty the cause. Presumably all works ok during a “session” on your PC but sometimes (or always?) fails after a reboot. This is likely to be associated with a failure of the graphics device driver to enumerate the monitors in a consistent way. Suggest updating the graphics driver as a start.

**Comment by AntonyCorbett** [comment] 2023-04-18 16:34
Closing for now, but please let me know if you have any further observations.

**Closed by AntonyCorbett** 2023-04-18 16:34 UTC
