### ISSUE TITLE
5 min timer before meeting

### ISSUE THREAD

**Issue by Passarito** [AntonyCorbett/OnlyT#19] opened 2017-09-22 20:13 UTC
First, thanks for all the effort and simple but beautiful design!

An interesting option would be a 5 min timer for the meeting start. The aplication would look for the nearest 15 min hour division, and 5 min before, it could draw a blue sector counting down 5 min for the meeting start.

**Comment by TechMan88** [comment] 2017-09-29 14:56
30 min increments wouldbe better , like sound box. thank you Anthony for helping making our Meetings easier.

**Comment by Passarito** [comment] 2017-09-29 18:34
In my kingdom hall there is a congregation starting the meeting at 10:15 a.m. That's why I suggested the 15 min interval.

**Comment by AntonyCorbett** [comment] 2017-12-14 18:09
Would the countdowtimer be useful (bearing in mind it would typically be displayed on the timer monitor rather than the media monitors)?

**Comment by Passarito** [comment] 2017-12-22 01:39
Well, in my kingdom hall the countdown monitor is pretty visible for the audience, as it stays on the back wall, so it would help. I have seen similar position in other kingdom halls, but also some others have the timer monitor nearly visible from the platform.

**Comment by pepekall** [comment] 2017-12-29 13:01
I hope this feature is coming soon now when we stop using Sounbox

**Comment by MrPaulus** [comment] 2017-12-30 09:20
A countdown timer, even on just the timer screen, would be very useful. The current version in Soundbox certainly helps our meetings start on time!

**Comment by AntonyCorbett** [comment] 2018-01-06 14:04
@MrPaulus - thanks. The talk_schedule.xml file is not used in automatic mode. However, we could add meeting start times in the Settings page,

**Comment by AntonyCorbett** [comment] 2018-01-08 16:44
Started work on this new feature. Settings page to include meeting start times. Countdown to be displayed on timer monitor (not media monitor since JWL is to be used for background image before the meeting)

**Comment by TechMan88** [comment] 2018-01-08 16:46
Thank you Anthony for all your generous work. 

Sent from Yahoo Mail on Android 
 
  On Mon, Jan 8, 2018 at 8:44 AM, Antony Corbett<notifications@github.com> wrote:   
Started work on this new feature. Settings page to include meeting start times. Countdown to be displayed on timer monitor (not media monitor since JWL is to be used for background image before the meeting)

**Comment by Passarito** [comment] 2018-01-09 21:16
Dear Antony, I am very pleased to know you are taking care of this topic. While developing it, please consider the kingdom halls serving several congregations where there can be different start times for the meeting, namely at the weekend.

**Comment by AntonyCorbett** [comment] 2018-01-09 22:28
@Passarito >> please consider the kingdom halls serving several congregations << 
Thanks - understood.

**Comment by Chipperchap** [comment] 2018-01-12 08:30
So as I understand it, OnlyT will work on the timer screen with almost full functionality we are accustomed to with SoundBox... with the exception of having the pre-meeting countdown timer on the main auditorium screens as it cannot override JWL.  
Is that correct?  
I notice that VLC, when enabled to show an image for example, will override JWL, so that JWL has to be toggled on again (using the taskbar icon), so I guess it would be a similar issue with OnlyT...

**Comment by AntonyCorbett** [comment] 2018-01-12 09:14
@Chipperchap 

> almost full functionality we are accustomed to with SoundBox

Yes, but limited to the timing functions of course :)

> exception of having the pre-meeting countdown timer on the main auditorium screens as it cannot override JWL.

It's not that it _cannot_. It's up to you to select a timer monitor in OnlyT, and if you choose the media monitor it will override JWL display. However, I have chosen to limit OnlyT to a single monitor which means you would need to go out of your way to display the countdown on the media monitor. This is by design as the instructions state that the year text (as provided in JWL) should be displayed before and after meetings. Accordingly, I feel that it would be inappropriate to allow OnlyT to undermine the instruction so easily (or even to overlay the countdown in a corner of the year text). It's only my personal view of course, and it may change over time.

**Comment by Chipperchap** [comment] 2018-01-12 13:35
I appreciate your comments and deeply respect your desiring to be obedient to the instruction provided.  Well done! 

> Yes, but limited to the timing functions of course :)

Yes, of course :-)

My mention is a selfish one rather than adhering strictly to 'screen use protocol'... the congregation friends have become used to seeing the countdown timer, the chairman uses it to start the meeting on time; this is similar to what we have become accustomed to with an official countdown timer at regional convention level. 

> This is by design as the instructions state that the year text (as provided in JWL) should be displayed before and after meetings. 

True...
> Letter Dec 2, 2017 Par. 46 Bullet 2:  "The digital yeartext should be displayed before the opening song, after the concluding prayer, **and during the meeting** when nothing else is being shown on the screens."

We have locally chosen to do away with a static display for this reason, (it being shown on the screens).

I suppose my thought is that there is the 'implied permission' to emulate what is shown at regional convention level, (if the BOE agrees too).  That convention standard is what we strive to achieve for other congregational activities.  
Also, since the YearText is displayed almost continually by JWL, having a, even discrete (corner of screen), countdown will hardly interfere with the meeting program while honouring the spirit of the letter. 

_Smile_

May I also add to the chorus of expressions of appreciation to you and the team for what you have done over the last few years with SoundBox and associated applications.  It has truly assisted us to enjoy the meetings more with software that made things so much easier - removing much of the stress and distraction of using alternative programs.  Thank you!

**Comment by ricardoantonio** [comment] 2018-01-13 02:42
Usually, when we want to know how much time is needed for the meeting to start, we tend to look at the clock that is in the back of the Kingdom Hall. And there is no clearer indication that the meeting is going to start than to see the president stand in front of the lectern.

I like the idea of the counter, but sticking to the instructions, there is no need to burden our brother with more work by having him project the counter on the screens where the text of the year should appear at all times.

**Comment by AntonyCorbett** [comment] 2018-01-15 06:08
@Passarito @TechMan88 @pepekall @MrPaulus @Chipperchap 

Pre-release available with countdown:

https://github.com/AntonyCorbett/OnlyT/releases/tag/1.0.0.39

**Comment by Chipperchap** [comment] 2018-01-15 09:03
Thank you for 1.0.0.39. - tested this evening.

I notice that the meeting times for the countdown timer are 24 hour settings; no problem. :-)

I enabled twice and got the same results - a bug.
The countdown timer starts but immediately shuts down from displaying on the second screen (monitor).  If I select another screen it shows briefly then disappears again.  OnlyT is somehow running in the background and cannot be stopped, restarted or similar.  (Or at least I don't know how :-) ) After the five minutes are up, the second screen (monitor) can be once again selected from the droplist and will stay open.
If attempting to view within the five minute countdown the computer has to be restarted to force OnlyT to shut down.

**Comment by AntonyCorbett** [comment] 2018-01-15 09:35
@Chipperchap - thanks for testing. Please would you explain the steps needed to reproduce the problem. I got lost at "I enabled twice" :)

**Comment by Chipperchap** [comment] 2018-01-15 14:16
Reworded:
Twice I loaded / started the program and each time got the same results.   
Process:
Created a time in the meeting times box and enabled countdown
![image](https://user-images.githubusercontent.com/35364657/34946093-5e6f62cc-fa6a-11e7-9da6-c0763fac73b1.png)
When the time came around, the countdown timer flashed up on my secondary screen (I run two screens / monitors on my home PC) but then disappeared.  
Toggling between screens would show that the countdown was working but would, after a moment, disappear. 
![image](https://user-images.githubusercontent.com/35364657/34946220-df205cdc-fa6a-11e7-991d-c3b9a894660d.png)
There was no way via any method I know of (task manager, alt+tab) to view the countdown timer in operation nor in any way shut it down to start again.

[I would produce a screenshot video but it is 3:13am and I only got up to get a glass of water :-) 
If I can find time between jobs tomorrow I will give it a try.]

**Comment by ricardoantonio** [comment] 2018-01-15 14:18
I tested the application on a single monitor. When the counter must start, the clock disappears. But as i can read, i have the same problem as @Chipperchap 


(Sorry for my english)

**Comment by AntonyCorbett** [comment] 2018-01-16 16:09
@Chipperchap @ricardoantonio Thanks for feedback. The installer had a missing file. Now fixed.

https://github.com/AntonyCorbett/OnlyT/releases/tag/1.0.0.40

**Comment by ricardoantonio** [comment] 2018-01-16 16:42
I'll test at night. Now I'm at work and then I have my midweek meeting. Tanks for your hard work.

**Comment by Chipperchap** [comment] 2018-01-17 00:11
I have only had a little play but 1.0.0.40 appears to be working fine.  Little clip of it working [HERE ](https://youtu.be/HxEDfRgny_s).

What I especially like is that if OnlyT is shut down and reopened a moment later, the countdown timer works if still within the 5 minute timer period, displaying the remaining time.

**Comment by Passarito** [comment] 2018-01-17 23:45
I have also played with 1.0.0.40 at home, single monitor. It works fine, the solution you found for several congregations in the same kingdom hall is really simple and versatile! By the way, the week day needs to be entered in local language. If inserted in english, the program picks a day from the local languange and it may not be the correct one. For instance, I inserted **sat 18:00** but it changed to **seg 18:00**, which is monday in portuguese. If I insert in portuguese, it is ok. By the way, trying to insert **dom 10:00** (sunday) reverts to **dom 22:00**. The conversion always to pm hours is not desired in this particular case. 
I have also noticed the same behavior @Chipperchap commented just before me, which is really fine.

Thanks a lot for your excelente work - and patience!

**Comment by AntonyCorbett** [comment] 2018-01-19 09:38
@Passarito - thanks for your help with this bug, Now fixed.

https://github.com/AntonyCorbett/OnlyT/releases/tag/1.0.0.41

**Comment by ricardoantonio** [comment] 2018-02-03 03:39
I am very grateful for your work. It has been very useful in the congregation.
Is there a way to see the digital clock below the countdown?

**Comment by AntonyCorbett** [comment] 2018-02-03 12:39
@ricardoantonio - sorry the tiem of day is not shown when the countdown is displayed.

**Closed** 2018-02-14 16:14 UTC
Labels: enhancement
