### ISSUE TITLE
Click on setup icon: only T Closes

### ISSUE THREAD

**Issue by Jeffreyd2** [AntonyCorbett/OnlyT#144] opened 2018-10-31 13:02 UTC
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows version
 - Other important information about your environment

**Comment by AntonyCorbett** [comment] 2018-10-31 13:58
@Jeffreyd2 Thanks for your report. Please would you explain exactly what the problem is? Thanks, Antony

**Comment by Jeffreyd2** [comment] 2018-10-31 15:13
I installed Only TClicked on settings icon.Only T closes.I removed the program and downloaded a new file. Installed.Clicked on settings icon and only t closes.I also downloaded Only M, Only V, and Only R.


Jeffrey L. Doughman
ASE Certified 
Master Automotive Technician
     
http://www.fetchandfix.com
http://www.themotoroilpro.com


jeffrey@fetchandfix.com 
570-832-4445
 

    On Wednesday, October 31, 2018, 9:59:14 AM EDT, Antony Corbett <notifications@github.com> wrote:  
 
 
@Jeffreyd2 Thanks for your report. Please would you explain exactly what the problem is? Thanks, Antony

**Comment by AntonyCorbett** [comment] 2018-11-09 07:18
@Jeffreyd2 I am closing the issue for now as there has been no further activity, but please reopen if necessary.

**Closed by AntonyCorbett** 2018-11-09 07:18 UTC
Labels: question
