### ISSUE TITLE
enable/disabile timer for duplicate monitor jw library

### ISSUE THREAD

**Issue by marinosalvatore** [AntonyCorbett/OnlyT#293] opened 2019-03-10 16:19 UTC
Hi, I would like to ask if you can add a very useful new feature. Since jw library there is no third screen function if you can make sure that when I have to project an image on the screen to temporarily disable the chronometer and duplicate the second with the third screen. While when I remove the image, divide the screens and re-enable the stopwatch.

**Comment by AntonyCorbett** [comment] 2019-03-17 08:19
See #234

**Comment by marinosalvatore** [comment] 2019-03-20 13:02
I saw # 234 but I meant to say something else. Currently we have three monitors (main PC, secondary time and tertiary video images) all three monitors in full, to be able to show the images instead of time I have to duplicate the second with the third screen and the other way around to be able to see the time in the second screen, but the problem that once you change the setting of the monitors I have to close the programs and reopen them to view everything as it was.
In order to take inspiration, I am attaching a link with the code: http://knowhowshare.blogspot.com/2012/03/display-switch-in-window-7-with-vb.html?m=1

**Comment by AntonyCorbett** [comment] 2019-03-20 13:23
@marinosalvatore Thanks - I think I understand now. You have 3 monitors as follows:

1. Main PC
2. Media
3. Timer

These are normally used in "extended desktop" mode so that they can each show different content. However, when an image is shown or video played you want to be able to clone ("mirror") the media display on the timer display so that the timer display shows the media too. Then when the media is finished you need to be able to revert to 3 extended displays. It looks like you can already do the switching of display modes but the problem is that one or more applications must be restarted after the switch because the mode switch messes up their display configuration. Do I understand correctly?

So a solution might be to modify the affected applications to accommodate a change in display mode. For example, if OnlyT detects that its monitor is now a clone of another monitor it could just close its timer display, then when it detects that the monitor is extended once more it could redisplay the timer window.

BTW, AFAIK, the ability to have 2 monitors mirrored and another extended is dependent on the capability of the graphics card/driver - it is not simply a native Windows setting.

**Comment by marinosalvatore** [comment] 2019-03-20 13:32
yes and correct, you got it right. That's why I wanted that extra button on OnlyT as I showed you on the image I sent you on Messenger fb.

**Comment by AntonyCorbett** [comment] 2019-03-20 14:35
With an extra switch you'd have a lot to do in order to show media, i.e.:

1. Turn off the OnlyT display
2. Switch to mirror mode
3. Display media

Have you thought about using a hardware splitter and switch?

**Comment by marinosalvatore** [comment] 2019-03-21 12:29
I understood what you mean, years ago I talked about it with my congregation elders but they didn't want to buy it and now they want to save. However I found a solution, I duplicate the screens 2 and 3, and the time I show it on a smartphone placed on the desk by ip address.

**Comment by KenFrantz** [comment] 2019-03-21 19:31
Good morning, Brothers. We in Casa Grande, Arizona also wanted to be able to show media on the timer monitor. Our monitor hangs from the ceiling about 8 feet in front of the stage. We tried using the hardware switch and splitter. It did not work well. the switching was very slow and sometimes the monitor never did pick up the change. Worse, when we switched back to the timer screen, it did not always go back. We even bought a new PC with a separate video card so we could use identical connection protocols to each monitor. But we could not get it to work acceptably.

**Comment by marinosalvatore** [comment] 2019-03-21 23:00
hello brother, you should do as I did, go to screen settings and duplicate the 2 with 3. Then take a smartphone connect it with the same wifi network as the PC, and through the OnlyT program set the ip address in the browser of the smartphone to see the timer and put it on the podium.

**Comment by marinosalvatore** [comment] 2019-03-21 23:03
![](https://i.imgur.com/jMIILif.jpg)

**Comment by ucphinni** [comment] 2019-03-22 11:37
Sorry if this solution does not fit your requirements in advance but this is what our congregation does.

We use OBS to copy the audience consumption monitor to the chairman monitor and append to the bottom of the screen the onlyt service web page. With various OBS scenes, we can even transition to speaker messages on the screen which flash momentarily in order to get the speaker's attention.

This solution is very flexible as we do not just use it for only t only. We have used it with webcams and the mic in from the sound system for streaming to another kingdom hall as well as recording training videos, wedding talks, funerals, and our LDC Kingdom Hall dedication.

This type of setup seems optimal for our congregation but requires some forethought in order to get it right. We use a little JavaScript, CSS and HTML we found on the web to get what we want but this is not required knowledge

[Image]

**Comment by marinosalvatore** [comment] 2019-03-22 13:33
sorry, I didn't understand and I can't see the attached image

**Comment by TizianoNoto** [comment] 2019-03-24 17:39
Ciao @marinosalvatore 

What @ucphinni tries to say is that they use [Open Broadcaster Software](https://obsproject.com/) to combine the media output with the timer and send the result to the timer monitor. You can use it to simply switch between media and time without disruption, if you prefer.

In our Hall I set up a special VLC shortcut so that it opens in full screen mode on the media displays and mirrors the content of one of the other monitors. The player is then closed from the taskbar. You can set it up to mirror the output for the media display(s) on the timer monitor, however it will cover the timer until closed.

**Comment by Spenser715** [comment] 2019-03-27 03:01
@ucphinni Thank you for the info on the WebClock in OBS. I was testing an option of using OBS but I wasn't able to get it to work until i added that. And with a few settings adjusted I am hoping to implement this option with no added hardware.

**Comment by ucphinni** [comment] 2019-03-27 23:21
There a couple of basic tricks that may help out with cpu and performance.

@Spenser715 Make sure you get the latest obs. Newest version uses gpu
offloading with both the video and more recently the browser containing obs.
Make sure the canvas is scaled to no higher than 1280x720
The frame rate for the audience monitor can be 15 or 10 fps
The onlyt webpage should be 2 fps.

In settings, Minimize to the toolbar. This helps eliminate acidential
changes and also speeds up rendering as OBS does not have to render its own
screen, just the projected confidence monitor.

These changes along should decrease cpu utilization by 55%. Our
congregation is routing the display through another computer as our main
computer only supports two monitors so you should be able to get better
performance than us.

Onlyt must start before obs, else you must manually refresh the webpage
browser from obs. I am working on a webpage hack to eliminate this
dependency. There are other tricks as well.

**Comment by Spenser715** [comment] 2019-03-27 23:43
@ucphinni thank you for the tips. I did find the issue of onlyt needing to start first. I solved this very simply by putting a 1 before the onlyt shortcut file name and a 2 before obs shortcut filename in the startup folder. I also set the taskbar up in a way that the projector window does not show on the media control monitor (to avoid accident closes)

**Comment by scottys94** [comment] 2019-03-28 00:44
>@ucphinni thank you for the tips. I did find the issue of onlyt needing to start first. I solved this very simply by putting a 1 before the onlyt shortcut file name and a 2 before obs shortcut filename in the startup folder. I also set the taskbar up in a way that the projector window does not show on the media control monitor (to avoid accident closes)

@Spenser715 How did you configure the taskbar to not show the projector window? I am looking for ways to do the same thing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Spenser715** [comment] 2019-03-28 00:50
@scottys94 I set the taskbar to be on all displays but i set them to only show programs that are on those displays. since the 2 second displays (media and timer) have full screen content you don't see the taskbars but the icons for the programs on those screens doesn't show.

**Comment by ucphinni** [comment] 2019-03-28 03:20
Even with the 1onlyt, but 2obs, we get in the case where obs initializes first before onlyt and then no timer webpage. It happens seldom but enough where the brothers had to be trained to refresh the onlyt portion to display the timer when this happens. I do not know why it takes so long.
________________________________

**Comment by Spenser715** [comment] 2019-03-28 04:42
Perhaps add in some buffers. Such as keep 1onlyt but then add some redundant startups just to add delay for number 2-5 then have obs as 6 or something like that. I'm not sure exactly what you would use but just an idea

**Comment by ucphinni** [comment] 2019-03-28 11:45
Idea was to capture the html from the onlyt webserver and dump to file to be used as the obs browser plugin file directly. This has polling retry logic and could be used to bootstrap in the event onlyt does not come up fast enough.

I will try to get this done this weekend. Hopefully, i will post results if this works.
________________________________

**Comment by TizianoNoto** [comment] 2019-03-28 12:30
@Spenser715  @ucphinni  Since you're discussing about the Startup folder I wanted to note that the use of the Startup folders is **deprecated** in Windows 10. I'd recommend using the **Task Scheduler** as you can set a timer before performing the activities and ensure that OBS always starts after OnlyT has finished loading.

**Comment by Spenser715** [comment] 2019-03-29 19:56
@TizianoNoto I'm not sure what you mean about the startup folder being depricated. I have a Windows 10 PC at home that I use as my test PC for all the KH software and I am able to use the startup folder just fine on it. However to your point being able to set the delay is a handy feature. I will look into that one.

**Comment by richfrantz** [comment] 2019-03-29 20:30
I've not seen anything stating it was deprecated. But if it is, it means it is on life support and will be removed in a future release. This allows people time to move on before things break.
________________________________

**Comment by Spenser715** [comment] 2019-03-29 20:44
@TizianoNoto in reference to starting OBS with Task Scheduler have you (or anyone else) figured out how to do this. I keep getting local errors.

**Comment by TizianoNoto** [comment] 2019-03-30 11:25
@Spenser715 @richfrantz I remembered reading that in the TechNet site but I can't find it, so I may actually be wrong. After a brief research this is what I can confirm:
- MS has intentionally hid the _Startup_ folders from the start menu
- desktop / classic applications will run fine from it
- UWP / modern apps shouldn't be put there because thay may have problems (it happened to me with JWL)

As soon as I'm on my pc I'll make some test

**Comment by TizianoNoto** [comment] 2019-03-30 11:27
@Spenser715 @richfrantz I remember reading that in the Technet site but I can't find it, so I may actually be wrong. After a quick research this is what I can confirm:
- MS has intentionally hid the _Startup_ folders from the start menu
- desktop / classic applications will run fine from it
- UWP / modern apps shouldn't be put there because thay may have problems (it happened to me with JWL)

As soon as I'm on my pc I'll make some tests

**Comment by Spenser715** [comment] 2019-04-01 03:31
@ucphinni @TizianoNoto So I tested with a Batch file to start the files in the correct order and have a shortcut to the .bat in the startup folder. This has been working nicely on all my tests although the sleep function has not been working as expected. But even with that glitch it still works fine.

**Comment by richfrantz** [comment] 2019-04-01 15:48
It was just moved is all. User specific now. On my PC

C:\Users\<your-user-name>\AppData\Roaming\Microsoft\Windows\Start Menu


________________________________

**Closed** 2019-05-09 15:38 UTC
Labels: question
