### ISSUE TITLE
Cannot get list of Monitors to appear in dropdown

### ISSUE THREAD

**Issue by tompkinsjs** [AntonyCorbett/OnlyT#55] opened 2018-01-27 00:14 UTC
We've got 2 HDMI and 1 USB monitor attached to the Win 10 PC and I cannot get the list of monitors to appear in the dropdown to have it display in another monitor.  Everything else seems to work just fine.

**Comment by AntonyCorbett** [comment] 2018-01-27 09:00
@tompkinsjs - are you using the latest version? Also, is the Windows desktop extended (which is what is required to have the monitors listed separately)?

**Comment by AntonyCorbett** [comment] 2018-02-01 11:11
@tompkinsjs. Closing - no response

**Comment by tompkinsjs** [comment] 2018-02-03 16:09
Sorry, I have been out of town and unable to verify the settings you wanted me to check.  I still have the same issue and the desktop is extended and I am running .43 on Win 10 version 1709.  The interesting things is that SoundBox works fine and displays the monitors as does other software.  Would it be possible for me to manually add the monitor string to the .json file?  Thanks.

**Comment by TechMan88** [comment] 2018-02-03 16:11
Only T working fine for me no problems. All monitors display on ours. Thxs Anthony

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 3, 2018 at 8:09 AM, tompkinsjs<notifications@github.com> wrote:   
Sorry, I have been out of town and unable to verify the settings you wanted me to check. I still have the same issue and the desktop is extended and I am running .43 on Win 10 version 1709. The interesting things is that SoundBox works fine and displays the monitors as does other software. Would it be possible for me to manually add the monitor string to the .json file? Thanks.

**Comment by AntonyCorbett** [comment] 2018-02-03 16:29
@tompkinsjs - I need to find out more about this. Will be in touch

**Comment by AntonyCorbett** [comment] 2018-02-04 16:38
@tompkinsjs - you say everything else works fine. Does that mean that you have been able to select a monitor in the dropdown? I assume not. So does the drop down work but is empty, or not work at all?

**Comment by AntonyCorbett** [comment] 2018-02-04 16:53
@tompkinsjs - please would you help me investigate by installing the latest release (v1.0.0.45). Run OnlyT, open the Settings page, close down and then send me the log for the day (In Documents\OnlyT)?

**Comment by tompkinsjs** [comment] 2018-02-11 21:05
[log-20180211.txt](https://github.com/AntonyCorbett/OnlyT/files/1714836/log-20180211.txt)

Log attached.  Sorry for taking so long to get back to you.  Still no monitors in the drop down in .45.

Thanks, Scott

**Comment by tompkinsjs** [comment] 2018-02-11 21:10
Screen shot attached in case it helps.

![capture](https://user-images.githubusercontent.com/35855516/36078556-b3d258fe-0f3d-11e8-9174-549403923a05.PNG)

**Comment by AntonyCorbett** [comment] 2018-02-12 14:51
@tompkinsjs - please would you try the latest release? https://github.com/AntonyCorbett/OnlyT/releases/latest

**Comment by tompkinsjs** [comment] 2018-02-16 23:28
Sorry. Still does not work.  Is there a way I could manually add the monitor to a configuration file?  Thanks for all of your help.  I have attached the log,
[log-20180216.txt](https://github.com/AntonyCorbett/OnlyT/files/1733127/log-20180216.txt)

**Comment by AntonyCorbett** [comment] 2018-02-17 09:17
@tompkinsjs - sorry there's no way to manually add monitor details. I'd like to get to the bottom of the problem here if you're still willing to help, but I have reviewed the code and the log files and I can't see why the call to EnumDisplayDevices is failing. Is there anything unusual about the machine or setup? Does it work when the USB device is removed?

**Comment by tompkinsjs** [comment] 2018-02-23 00:38
Nothing unusual that I can think of.  Like I mentioned previously, we had been using the Soundbox application and it didn't have any problems finding the monitor.  Previous to that, we used a little app that I wrote in vb.net and that read the monitors as well.

Here's some specs in case it helps:
![image](https://user-images.githubusercontent.com/35855516/36571922-ceab491e-17fe-11e8-9010-121cf7278dcd.png)
![image](https://user-images.githubusercontent.com/35855516/36571961-e0cba422-17fe-11e8-91c8-6a0b8eb4961d.png)

At the moment, I don't have a USB monitor attached.  We are using a direct HDMI connection to one monitor and to the others we connect via HDMI switch.

Just to try it, I did connect the USB monitor connection but that did not change anything.

Thanks for your help!

**Comment by AntonyCorbett** [comment] 2018-02-23 08:47
@tompkinsjs - perhaps you could take a look at the code and your log files and see where the 2nd call to EnumDisplayDevices is failing

**Comment by jammypd** [comment] 2018-02-26 15:37
Good morning,

If it helps, we're experiencing a similar situation with our set up at the Kingdom Hall - the drop-down list is blank. The 3rd  monitor is working and extended, we can work around the issue by dragging across a browser and using the timer that way but it is cumbersome. Is there any information on the set-up of our laptop that you need? We have the 2nd monitor for JW Library plugged into the HDMI socket of our laptop and the 3rd monitor (which is for the timer) plugged into a usb docking station (WAVLINK USB 3.0 / USB C Ultra 5K Universal Docking Station).
Kind regards

**Comment by omaha4** [comment] 2018-02-26 18:57
No dice for me with 1.0.0.47 on my Surface Book.  Works just fine with Sound Box. The crazy part is, it works just fine when three monitors are being extended, but not two.
![2018-02-26](https://user-images.githubusercontent.com/32815829/36688788-1fe1f476-1af3-11e8-97ed-0eb2c4bef28e.png)

 
![2018-02-26 2](https://user-images.githubusercontent.com/32815829/36689162-44373588-1af4-11e8-9b1a-1407c41b4003.jpg)

**Comment by AntonyCorbett** [comment] 2018-02-26 19:38
@omaha4 Thanks for feedback. the screenshots seem to show that the dropdown is populated in both cases (whether you have 2 or 3 monitors). What is the problem you are reporting please?

**Comment by omaha4** [comment] 2018-02-26 20:03
I apologize, this may have needed a new thread but is seems related. The left side of the screens are the primary( the surface book), while the middle and right sides are the secondary displays. As seen in the first screen shot, While the secondary display is selected for display, it places the timer display on the Surface book. I have tried multiple displays with the same results, it acts like the monitor is not even there. However, when three monitors are being used, the software treats the third display as it should, as seen in the second screen shot. There have been instances where I needed a second computer solution for a time out fear that JW Library will go haywire if it used with multiple windows (It happens more than it should. Having words on the screen and with no music is no fun)

**Comment by AntonyCorbett** [comment] 2018-02-26 21:19
@omaha4 - thanks. The problem you describe is usually a result of outdated or generic video drivers. Please update the drivers so that you don't get the "Generic pnp" designation.

**Comment by AntonyCorbett** [comment] 2018-03-02 17:01
@jammypd - let me know when you have an update please

**Comment by jammypd** [comment] 2018-03-02 22:01
Hi there, sorry for the delay - we should be able to get to the hall in the morning so will test it then and let you know straight away.On 2 Mar 2018 17:01, Antony Corbett <notifications@github.com> wrote:@jammypd - let me know when you have an update please

**Comment by jammypd** [comment] 2018-03-05 15:51
Hi, still not working for me - the dropdown list just displays the clock on the laptop screen when selected. I'm not sure if it's related at all or just a Windows 10 driver problem, but whenever I reboot, the laptop 'forgets' the 3rd monitor that is plugged into the docking station and I have to then remove and plug back in the HDMI cable.

**Comment by AntonyCorbett** [comment] 2018-03-07 17:36
@jammypd does it show the main monitor in the list when you don't have any external monitors plugged in?

**Comment by AntonyCorbett** [comment] 2018-03-08 08:36
@tompkinsjs - I believe this is an issue with the display driver. The monitor enumeration code is correct but the Windows API "EnumDisplayDevices" is returning false.

**Comment by dazzathestag** [comment] 2018-03-14 17:40
![img_1924](https://user-images.githubusercontent.com/37379816/37420408-9b62db20-27ae-11e8-911b-119a1994a75e.JPG)
Hi Anthony - Im in the same congregation as @jammypd just for clarification. Had another look today and all the monitor drivers are up to date although they are Generic Pnp Monitors as you can see

**Comment by dazzathestag** [comment] 2018-03-14 17:43
![img_1925](https://user-images.githubusercontent.com/37379816/37420506-d9534a32-27ae-11e8-8f2d-c371add3ad8d.JPG)
We do get all three monitors showing on the Only T App as shown but it doesnt matter which one we choose all that happens is that the timer appears on the laptop and takes the whole screen, ie always sits on top of everything else even though the button isnt clicked to ask it to sit on top as below
![img_1926](https://user-images.githubusercontent.com/37379816/37420649-2b0296bc-27af-11e8-845e-fe858a8e94c5.JPG)

**Comment by dazzathestag** [comment] 2018-03-14 17:45
I did try the Beta version this afternoon that you added the link for above however when I ran it it just presented an empty box
![img_1922](https://user-images.githubusercontent.com/37379816/37420710-5b4b77ee-27af-11e8-89dd-ac9290f0b8bd.JPG)
![img_1923](https://user-images.githubusercontent.com/37379816/37420721-61b401fa-27af-11e8-882b-bd083c3fe1dc.JPG)

**Comment by dazzathestag** [comment] 2018-03-14 17:48
Hope that helps in some way and if you have any other ideas then please let me know. I also took a snap of the windows display screen to show all 3 showing there. Although we have 3 external monitors and the laptop two of the monitors at the front are just split from the same signal hence even when all four screens are running we only see three on the windows Display page.
Thank you !!

**Comment by AntonyCorbett** [comment] 2018-03-14 18:51
@dazzathestag I believe the problem is associated with the display driver. You should find and install the correct driver for your card (they shouldn't shown as "generic").

**Comment by dazzathestag** [comment] 2018-03-14 19:24
I guess that to do that I would need to know the Make of the monitor and go to the manufacturers website to see if they had a specific driver - if thats the case Im stuck because thats what i tried to do today and believe it or not I couldn't find any make or model name on the monitors anywhere, or on the on screen menu/setup pages. We no longer have the boxes and don't seem to have any paperwork. They all came as the standard package - I don't suppose you know the make they issued us all with ? ( long shot i know !!)

**Comment by AntonyCorbett** [comment] 2018-03-14 19:39
@dazzathestag have you tried disabling the unused graphics adapter?

**Comment by dazzathestag** [comment] 2018-03-14 19:42
No - do you mean either the intel one or the Nvidia. Is graphics adapter the same as a Display Adapter ?

**Comment by AntonyCorbett** [comment] 2018-03-14 20:11
@dazzathestag Yes "graphics adapter" = "display adapter". I suspect it's the Intel on-board adapter that is not being used,

**Comment by dazzathestag** [comment] 2018-03-14 20:15
Thanks - will try that tomorrow night

**Comment by dazzathestag** [comment] 2018-03-15 21:41
Tried disabling the intel graphics adapter tonight (on the basis that the nvidia card is the more powerful one) and on rebooting whilst the initial Dell sign came up on the laptop screen and we could see the mouse pointer nothing else could be seen. Didn’t have time to try much else so I think I will need to go into safemode and try and switch that graphics adapter back on. 
I suppose I could try switching off the nvidia card but the reason we purchased that laptop was the benefit of having a better graphics card as we were having some problems with the previous laptop with only the built in motherboard shared graphics card.
Any other suggestions welcomed !

**Comment by dazzathestag** [comment] 2018-03-24 06:49
Just thought I would give an update in case anyone else got to the same point. Disabling the graphics card didn’t work and just made the laptop run really slowly, apparently the laptop needs the intel card to run the laptops screen even if there is a faster graphics card built in as well.
The monitor that we were trying to display the timer on had an hdmi lead than ran to the sound pod, so I purchased and iOS-hdmi cable, set up an old iPhone 5c in the pod and used the facility to show the timer on a url on the iPhone, given that was then mirrored onto the monitor all was well.
The only issues were that you can’t lock the iPhone in landscape so you just have to ensure that the phone itself stays landscape and it’s not easy to get rid of the address bar from safari showing on the monitor, but it does work.

The time no longer seems to want to show the analogue / split version of the timers only the digital but again this isn’t critical
Thanks for all the help

**Closed** 2018-03-27 16:32 UTC
Labels: bug

**Comment by AntonyCorbett** [comment] 2018-06-01 07:14
I have changed the monitor detection code in v1.1.0.8. It should work ok now

**Comment by AntonyCorbett** [comment] 2018-06-01 07:42
@dazzathestag  it sounds like you might be in tablet mode.
